/** Keystone geometry. 32-unit square. Regenerated by scripts/build-keystone.mjs. */
export const KEYSTONE_VIEWBOX = "0 0 32 32";
export const KEYSTONE_RING =
  "M27.9996 12.8743A12.4 12.4 0 1 1 21.1619 4.7255L18.8099 9.8627A6.75 6.75 0 1 0 22.532 14.2985Z";
export const KEYSTONE_WEDGE =
  "M21.8214 5.0514A12.4 12.4 0 0 1 27.7931 12.1682L22.4196 13.9141A6.75 6.75 0 0 0 19.1689 10.0401Z";
